# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20180508_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_validated',
        ),
    ]
