# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0004_auto_20180509_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='employee_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='employee_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('user_id', 'training_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userhistory',
            unique_together=set([('user_id', 'content_id')]),
        ),
    ]
