# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20180509_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='path',
            field=models.FileField(upload_to=b''),
        ),
    ]
