# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0006_auto_20180510_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assignment',
            name='training_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.Training'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('user_id', 'training_id')]),
        ),
    ]
